IF EXISTS
(
    SELECT *
    FROM sys.objects
    WHERE type = 'P'
          AND name = 'InsertDataToTableVBRP'
)
    DROP PROCEDURE InsertDataToTableVBRP;
GO
CREATE PROCEDURE [dbo].[InsertDataToTableVBRP]
AS
BEGIN

    DECLARE @_MinDate DATETIME;
    DECLARE @_MaxDate DATETIME;

    SELECT @_MinDate = MIN(CONVERT(DATE, PRSDT, 104)),
           @_MaxDate = MAX(CONVERT(DATE, PRSDT, 104))
    FROM dbo.TMP_DT0_vbrp;

    DELETE k
    FROM dbo.SAP_DT0_vbrp k
    WHERE CONVERT(DATE, PRSDT, 104)
    BETWEEN @_MinDate AND @_MaxDate;
	
    INSERT INTO dbo.SAP_DT0_vbrp
    (
        VBELN,
        POSNR,
        UEPOS,
        FKIMG,
        VRKME,
        MEINS,
        NTGEW,
        BRGEW,
        GEWEI,
        VOLUM,
        VOLEH,
        PRSDT,
        KURSK,
        NETWR,
        VGBEL,
        VGPOS,
        MATNR,
        ARKTX,
        CHARG,
        MATKL,
        PSTYV,
        POSAR,
        PRODH,
        VSTEL,
        SPART,
        WERKS,
        TAXM1,
        SKFBP,
        KONDM,
        KTGRM,
        VKBUR,
        SPARA,
        SHKZG,
        ERNAM,
        ERDAT,
        ERZET,
        LGORT,
        STAFO,
        WAVWR,
        KZWI1,
        KZWI2,
        KZWI3,
        KZWI4,
        KZWI5,
        KZWI6,
        PRCTR,
        KVGR1,
        KVGR2,
        MVGR1,
        MVGR2,
        MATWA,
        BONBA,
        KOSTL,
        PAOBJNR,
        CMPRE,
        BZIRK_AUFT,
        KONDA_AUFT,
        VKORG_AUFT,
        VTWEG_AUFT,
        AUTYP,
        KNUMA_AG,
        MWSBP,
        AUGRU_AUFT,
        BRTWR,
        KURSK_DAT,
        MSR_REFUND_CODE,
        MSR_RET_REASON,
        VGTYP,
        AUBEL,
        AUPOS,
        PRSFD,
        SKTOF,
        VKGRP
    )
    SELECT VBELN,
           POSNR,
           UEPOS,
           FKIMG,
           VRKME,
           MEINS,
           NTGEW,
           BRGEW,
           GEWEI,
           VOLUM,
           VOLEH,
           PRSDT,
           KURSK,
           NETWR,
           VGBEL,
           VGPOS,
           MATNR,
           ARKTX,
           CHARG,
           MATKL,
           PSTYV,
           POSAR,
           PRODH,
           VSTEL,
           SPART,
           WERKS,
           TAXM1,
           SKFBP,
           KONDM,
           KTGRM,
           VKBUR,
           SPARA,
           SHKZG,
           ERNAM,
           ERDAT,
           ERZET,
           LGORT,
           STAFO,
           WAVWR,
           KZWI1,
           KZWI2,
           KZWI3,
           KZWI4,
           KZWI5,
           KZWI6,
           PRCTR,
           KVGR1,
           KVGR2,
           MVGR1,
           MVGR2,
           MATWA,
           BONBA,
           KOSTL,
           PAOBJNR,
           CMPRE,
           BZIRK_AUFT,
           KONDA_AUFT,
           VKORG_AUFT,
           VTWEG_AUFT,
           AUTYP,
           KNUMA_AG,
           MWSBP,
           AUGRU_AUFT,
           BRTWR,
           KURSK_DAT,
           MSR_REFUND_CODE,
           MSR_RET_REASON,
           VGTYP,
           AUBEL,
           AUPOS,
           PRSFD,
           SKTOF,
           VKGRP
    FROM dbo.TMP_DT0_vbrp;

	TRUNCATE TABLE dbo.TMP_DT0_vbrp;
END;