USE MaisonDW;
IF NOT EXISTS
(
    SELECT *
    FROM sys.objects
    WHERE object_id = OBJECT_ID(N'TMP_DM0_mara')
          AND type IN ( N'U' )
) 
BEGIN
    CREATE TABLE [dbo].[TMP_DM0_mara]
    (
        [ID] [INT] IDENTITY(1, 1) NOT NULL,
        MATNR [NVARCHAR](2000) NULL,
        ERSDA [NVARCHAR](2000) NULL,
        ERNAM [NVARCHAR](2000) NULL,
        LAEDA [NVARCHAR](2000) NULL,
        PSTAT [NVARCHAR](2000) NULL,
        MTART [NVARCHAR](2000) NULL,
        MBRSH [NVARCHAR](2000) NULL,
        MATKL [NVARCHAR](2000) NULL,
        BISMT [NVARCHAR](2000) NULL,
        MEINS [NVARCHAR](2000) NULL,
        BRGEW [NVARCHAR](2000) NULL,
        NTGEW [NVARCHAR](2000) NULL,
        GEWEI [NVARCHAR](2000) NULL,
        VOLUM [NVARCHAR](2000) NULL,
        RAUBE [NVARCHAR](2000) NULL,
        SPART [NVARCHAR](2000) NULL,
        LAENG [NVARCHAR](2000) NULL,
        BREIT [NVARCHAR](2000) NULL,
        HOEHE [NVARCHAR](2000) NULL,
        MSTDE [NVARCHAR](2000) NULL,
        MSTDV [NVARCHAR](2000) NULL,
        TAKLV [NVARCHAR](2000) NULL,
        MHDRZ [NVARCHAR](2000) NULL,
        MHDHB [NVARCHAR](2000) NULL,
        MHDLP [NVARCHAR](2000) NULL,
        INHAL [NVARCHAR](2000) NULL,
        VPREH [NVARCHAR](2000) NULL,
        INHBR [NVARCHAR](2000) NULL,
        COMPL [NVARCHAR](2000) NULL,
        IPRKZ [NVARCHAR](2000) NULL,
        WHSTC [NVARCHAR](2000) NULL,
        WHMATGR [NVARCHAR](2000) NULL,
        [/BEV1/LULEINH] [NVARCHAR](2000) NULL,
        [/BEV1/LULDEGRP] [NVARCHAR](2000) NULL,
        VOLEH [NVARCHAR](2000) NULL,
        AENAM [NVARCHAR](2000) NULL,
        MFRPN [NVARCHAR](2000) NULL,
        MFRNR [NVARCHAR](2000) NULL,
        GROES [NVARCHAR](2000) NULL,
        LVORM [NVARCHAR](2000) NULL,
        AESZN [NVARCHAR](2000) NULL,
        FERTH [NVARCHAR](2000) NULL,
        EXTWG [NVARCHAR](2000) NULL,
        PRDHA [NVARCHAR](2000) NULL
            CONSTRAINT [PK_TMP_DM0_mara]
            PRIMARY KEY CLUSTERED ([ID] ASC)
            WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON,
                  ALLOW_PAGE_LOCKS = ON
                 ) ON [PRIMARY]
    ) ON [PRIMARY];
END;

GO
SET ANSI_PADDING OFF;
GO
