USE MaisonDW;
IF NOT EXISTS
(
    SELECT *
    FROM sys.objects
    WHERE object_id = OBJECT_ID(N'SAP_DT0_vbrk')
          AND type IN ( N'U' )
)
BEGIN
    CREATE TABLE [dbo].[SAP_DT0_vbrk]
    (
        [ID] [INT] IDENTITY(1, 1) NOT NULL,
        VBELN [NVARCHAR](2000) NULL,
        FKART [NVARCHAR](2000) NULL,
        FKTYP [NVARCHAR](2000) NULL,
        VBTYP [NVARCHAR](2000) NULL,
        WAERK [NVARCHAR](2000) NULL,
        VKORG [NVARCHAR](2000) NULL,
        VTWEG [NVARCHAR](2000) NULL,
        KALSM [NVARCHAR](2000) NULL,
        KNUMV [NVARCHAR](2000) NULL,
        VSBED [NVARCHAR](2000) NULL,
        FKDAT [NVARCHAR](2000) NULL,
        BELNR [NVARCHAR](2000) NULL,
        KDGRP [NVARCHAR](2000) NULL,
        BZIRK [NVARCHAR](2000) NULL,
        PLTYP [NVARCHAR](2000) NULL,
        RFBSK [NVARCHAR](2000) NULL,
        KURRF [NVARCHAR](2000) NULL,
        ZTERM [NVARCHAR](2000) NULL,
        KTGRD [NVARCHAR](2000) NULL,
        BUKRS [NVARCHAR](2000) NULL,
        TAXK1 [NVARCHAR](2000) NULL,
        NETWR [NVARCHAR](2000) NULL,
        ERNAM [NVARCHAR](2000) NULL,
        ERZET [NVARCHAR](2000) NULL,
        ERDAT [NVARCHAR](2000) NULL,
        STAFO [NVARCHAR](2000) NULL,
        KUNRG [NVARCHAR](2000) NULL,
        KUNAG [NVARCHAR](2000) NULL,
        AEDAT [NVARCHAR](2000) NULL,
        SFAKN [NVARCHAR](2000) NULL,
        STCEG [NVARCHAR](2000) NULL,
        FKART_RL [NVARCHAR](2000) NULL,
        FKDAT_RL [NVARCHAR](2000) NULL,
        MANSP [NVARCHAR](2000) NULL,
        SPART [NVARCHAR](2000) NULL,
        KKBER [NVARCHAR](2000) NULL,
        KNKLI [NVARCHAR](2000) NULL,
        CMWAE [NVARCHAR](2000) NULL,
        CMKUF [NVARCHAR](2000) NULL,
        HITYP_PR [NVARCHAR](2000) NULL,
        BSTNK_VF [NVARCHAR](2000) NULL,
        XBLNR [NVARCHAR](2000) NULL,
        ZUONR [NVARCHAR](2000) NULL,
        MWSBK [NVARCHAR](2000) NULL,
        FKSTO [NVARCHAR](2000) NULL,
        KURRF_DAT [NVARCHAR](2000) NULL,
        KIDNO [NVARCHAR](2000) NULL,
        BUPLA [NVARCHAR](2000) NULL,
        KNUMA [NVARCHAR](2000) NULL,
        LAND1 [NVARCHAR](2000) NULL
            CONSTRAINT [PK_SAP_DT0_vbrk]
            PRIMARY KEY CLUSTERED ([ID] ASC)
            WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON,
                  ALLOW_PAGE_LOCKS = ON
                 ) ON [PRIMARY]
    ) ON [PRIMARY];
END;

GO
SET ANSI_PADDING OFF;
GO
