USE MaisonDW
IF NOT EXISTS
(
    SELECT *
    FROM sys.objects
    WHERE object_id = OBJECT_ID(N'SAP_DT0_bsim')
          AND type IN ( N'U' )
)
BEGIN
    CREATE TABLE [dbo].[SAP_DT0_bsim]
    (
        [ID] [INT] IDENTITY(1, 1) NOT NULL,
        MATNR [NVARCHAR](2000) NULL,
        BWKEY [NVARCHAR](2000) NULL,
        BWTAR [NVARCHAR](2000) NULL,
        BELNR [NVARCHAR](2000) NULL,
        GJAHR [NVARCHAR](2000) NULL,
        BUZEI [NVARCHAR](2000) NULL,
        BUZID [NVARCHAR](2000) NULL,
        SHKZG [NVARCHAR](2000) NULL,
        DMBTR [NVARCHAR](2000) NULL,
        MENGE [NVARCHAR](2000) NULL,
        MEINS [NVARCHAR](2000) NULL,
        BUDAT [NVARCHAR](2000) NULL,
        BLDAT [NVARCHAR](2000) NULL,
        BLART [NVARCHAR](2000) NULL
            CONSTRAINT [PK_SAP_DT0_bsim]
            PRIMARY KEY CLUSTERED ([ID] ASC)
            WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON,
                  ALLOW_PAGE_LOCKS = ON
                 ) ON [PRIMARY]
    ) ON [PRIMARY];
END;

GO
SET ANSI_PADDING OFF;
GO
